apiVersion: v1
kind: Secret
metadata:
  name: iris-app-secrets
  namespace: iris-web
  labels:
    site: iris
type: Opaque
data:
  POSTGRES_USER: cmFwdG9y
  POSTGRES_PASSWORD: X19NVVNUX0JFX0NIQU5HRURfXw==
  POSTGRES_ADMIN_USER: cmFwdG9y
  POSTGRES_ADMIN_PASSWORD: X19NVVNUX0JFX0NIQU5HRURfXw==
  POSTGRES_PORT: NTQzMg==
  IRIS_SECRET_KEY: X19NVVNUX0JFX0NIQU5HRURfXw==
  IRIS_SECURITY_PASSWORD_SALT: X19NVVNUX0JFX0NIQU5HRURfXw==